stages:
  - test
  - build-push
  - kube-apply-dev
  - kube-apply-uat
  - kube-apply-prod

test:
  stage: test
  image: node:alpine
  script:
    - npm install
    - npm test

build-push:
  stage: build-push
  environment: dev
  image: docker:20-dind
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  script:
    - apk add --no-cache aws-cli
    - docker build -t 935537832940.dkr.ecr.ap-northeast-3.amazonaws.com/demo-web:latest .
    - aws ecr get-login-password --region ap-northeast-3 | docker login --username AWS --password-stdin 935537832940.dkr.ecr.ap-northeast-3.amazonaws.com
    - docker push 935537832940.dkr.ecr.ap-northeast-3.amazonaws.com/demo-web:latest

kube-apply-dev:
  stage: kube-apply-dev
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  environment: dev
  script:
    - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl && chmod +x ./kubectl
    - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
    - aws eks update-kubeconfig --name $CI_ENVIRONMENT_NAME-eks-cluster
    - kubectl apply -f web.yaml

kube-apply-uat:
  stage: kube-apply-uat
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  environment: dev
  script:
    - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl && chmod +x ./kubectl
    - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
    - aws eks update-kubeconfig --name $CI_ENVIRONMENT_NAME-eks-cluster
    - kubectl apply -f web.yaml
  when: manual

kube-apply-prod:
  stage: kube-apply-prod
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  environment: dev
  script:
    - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl && chmod +x ./kubectl
    - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
    - aws eks update-kubeconfig --name $CI_ENVIRONMENT_NAME-eks-cluster
    - kubectl apply -f web.yaml
  when: manual