apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-frontend
          image: 935537832940.dkr.ecr.ap-northeast-3.amazonaws.com/demo-web:latest
          ports:
            - containerPort: 3000